### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by NotLe0n** [TheLonelySheep/Creativetools#1]
Fuck multiplayer

**Comment by steviegt6** [comment]
Extremely professional. 10/10

**Comment by ghost** [comment]
fix that glitch dude

**Comment by steviegt6** [comment]
> 
> 
> fix that glitch dude

Yeah, fix _that_ glitch.

**Comment by NotLe0n** [comment]
> > 
> > 
> > fix that glitch dude
> 
> Yeah, fix _that_ glitch. 

Will u help ?
  🥺
👉👈

**Comment by steviegt6** [comment]
> 
> 
> > > fix that glitch dude
> > 
> > 
> > Yeah, fix _that_ glitch.
> 
> Will u help ?
> pleading_face
> point_rightpoint_left

No one willingly does netcode without a salary, sorry.

**Comment by NotLe0n** [comment]
Where is my salary? :(
